# Generated by Django 3.0.13 on 2021-03-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_auto_20210314_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded', models.DateField(auto_created=True)),
                ('detail', models.CharField(max_length=300)),
            ],
        ),
    ]
