# Generated by Django 3.0.13 on 2021-03-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_meetrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetrecord',
            name='recorded',
            field=models.DateField(auto_now_add=True),
        ),
    ]
